# Generated by Django 5.1.6 on 2025-02-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_userprofile_employee_code_userprofile_is_ldap_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
